import { ArrowUpRight, BriefcaseBusiness, FileText, Loader2, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { useEffect, useState } from "react";
import { api } from "../services/api";
import type { Case } from "../types";

const statusStyle = { uploaded: "bg-blue-500/10 text-blue-300", processing: "bg-amber-500/10 text-amber-300", ready: "bg-emerald-500/10 text-emerald-300", failed: "bg-red-500/10 text-red-300" };
export function DashboardPage() { const [cases, setCases] = useState<Case[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { api.listCases().then(setCases).catch(error => setError(error.message)).finally(() => setLoading(false)); }, []); const ready = cases.filter(item => item.status === "ready").length; return <><section className="mb-9"><p className="eyebrow">Your workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Prepare with clarity.</h1><p className="mt-3 max-w-xl text-zinc-400">Turn dense case files into a structured briefing your team can review before a hearing.</p></section><section className="grid gap-4 sm:grid-cols-3"><Metric icon={<BriefcaseBusiness/>} label="Case files" value={String(cases.length).padStart(2,"0")}/><Metric icon={<Sparkles/>} label="Reports ready" value={String(ready).padStart(2,"0")}/><Metric icon={<FileText/>} label="Pages processed" value={String(cases.reduce((sum, item) => sum + (item.page_count ?? 0), 0)).padStart(2,"0")}/></section><section className="surface mt-8 overflow-hidden"><div className="flex items-center justify-between border-b border-zinc-800 px-5 py-5 sm:px-6"><div><h2 className="font-semibold">Recent case files</h2><p className="mt-1 text-sm text-zinc-500">Analysis reports and their current status.</p></div><Link className="button-secondary" to="/upload">New case</Link></div>{loading ? <div className="grid place-items-center py-20 text-zinc-500"><Loader2 className="animate-spin"/></div> : error ? <p className="p-6 text-sm text-red-300">Could not reach the backend: {error}</p> : cases.length === 0 ? <EmptyState/> : <div className="divide-y divide-zinc-800">{cases.map(item => <Link key={item.id} to={`/cases/${item.id}`} className="group flex items-center gap-4 px-5 py-5 transition hover:bg-zinc-900/60 sm:px-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-zinc-800 text-zinc-300"><FileText size={18}/></span><div className="min-w-0 flex-1"><p className="truncate font-medium text-zinc-100">{item.title}</p><p className="mt-1 text-sm text-zinc-500">{item.page_count ?? "—"} pages · {new Date(item.created_at).toLocaleDateString()}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium capitalize ${statusStyle[item.status]}`}>{item.status}</span><ArrowUpRight size={18} className="text-zinc-600 transition group-hover:text-zinc-200"/></Link>)}</div>}</section></> }
function Metric({ icon, label, value }: { icon:React.ReactNode; label:string; value:string }) { return <div className="surface p-5"><div className="flex items-center justify-between text-zinc-500"><span className="eyebrow">{label}</span><span className="text-amber">{icon}</span></div><p className="mt-4 text-3xl font-semibold tracking-tight">{value}</p></div> }
function EmptyState() { return <div className="px-6 py-20 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-zinc-800 text-amber"><FileText size={21}/></span><h3 className="mt-4 font-medium">No cases yet</h3><p className="mt-2 text-sm text-zinc-500">Upload a PDF to create your first hearing-ready report.</p><Link to="/upload" className="button-primary mt-5">Upload case file</Link></div> }
